# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{divinity}
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Colin MacKenzie IV (sinisterchipmunk)"]
  s.date = %q{2009-12-08}
  s.description = %q{A new kind of game engine}
  s.email = %q{sinisterchipmunk@gmail.com}
  s.extensions = ["ext/divinity/extconf.rb"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "ext/divinity/array.c",
     "ext/divinity/divinity.c",
     "ext/divinity/divinity.h",
     "ext/divinity/divinity_macros.h",
     "ext/divinity/frustum.c",
     "ext/divinity/octree.c",
     "ext/divinity/octree_object_descriptor.c",
     "ext/divinity/open_gl.c",
     "ext/divinity/planes_and_vertices.c",
     "ext/divinity/render_helper.c",
     "ext/divinity/ruby.h",
     "ext/divinity/vertex3d.c",
     "lib/dependencies.rb",
     "lib/devices/input_device.rb",
     "lib/devices/keyboard.rb",
     "lib/devices/keyboard/modifiers.rb",
     "lib/devices/mouse.rb",
     "lib/divinity.rb",
     "lib/divinity_engine.rb",
     "lib/engine/cache.rb",
     "lib/engine/content.rb",
     "lib/engine/content_loader.rb",
     "lib/engine/content_module.rb",
     "lib/engine/controller.rb",
     "lib/engine/controller/base.rb",
     "lib/engine/controller/class_methods.rb",
     "lib/engine/controller/event_dispatching.rb",
     "lib/engine/controller/helpers.rb",
     "lib/engine/controller/input_device_proxy.rb",
     "lib/engine/controller/keyboard_proxy.rb",
     "lib/engine/controller/mouse_proxy.rb",
     "lib/engine/controller/request.rb",
     "lib/engine/controller/response.rb",
     "lib/engine/controller/routing.rb",
     "lib/engine/controller/view_paths.rb",
     "lib/engine/default_gui.rb",
     "lib/engine/default_render_block.rb",
     "lib/engine/default_update_block.rb",
     "lib/engine/delegation.rb",
     "lib/engine/model/base.rb",
     "lib/engine/view.rb",
     "lib/engine/view/base.rb",
     "lib/extensions/array.rb",
     "lib/extensions/bytes.rb",
     "lib/extensions/fixnum.rb",
     "lib/extensions/magick.rb",
     "lib/extensions/magick/image.rb",
     "lib/extensions/magick/image_list.rb",
     "lib/extensions/magick_extensions.rb",
     "lib/extensions/matrix.rb",
     "lib/extensions/numeric.rb",
     "lib/extensions/object.rb",
     "lib/extensions/string.rb",
     "lib/geometry.rb",
     "lib/geometry/dimension.rb",
     "lib/geometry/plane.rb",
     "lib/geometry/point.rb",
     "lib/geometry/rectangle.rb",
     "lib/geometry/vector3d.rb",
     "lib/geometry/vertex3d.rb",
     "lib/helpers/attribute_helper.rb",
     "lib/helpers/component_helper.rb",
     "lib/helpers/content_helper.rb",
     "lib/helpers/event_listening_helper.rb",
     "lib/helpers/render_helper.rb",
     "lib/interface/builder.rb",
     "lib/interface/builder/class_methods.rb",
     "lib/interface/components.rb",
     "lib/interface/components/button.rb",
     "lib/interface/components/button/button_mouse_listener.rb",
     "lib/interface/components/button/instance_methods.rb",
     "lib/interface/components/component.rb",
     "lib/interface/components/component/render_methods.rb",
     "lib/interface/components/image.rb",
     "lib/interface/components/image_button.rb",
     "lib/interface/components/image_selector.rb",
     "lib/interface/components/input_component.rb",
     "lib/interface/components/label.rb",
     "lib/interface/components/radio_button.rb",
     "lib/interface/components/text_area.rb",
     "lib/interface/components/text_field.rb",
     "lib/interface/components/title_bar.rb",
     "lib/interface/components/toggle_button.rb",
     "lib/interface/containers/container.rb",
     "lib/interface/containers/flip_panel.rb",
     "lib/interface/containers/frame.rb",
     "lib/interface/containers/panel.rb",
     "lib/interface/gui.rb",
     "lib/interface/layouts.rb",
     "lib/interface/layouts/alignment.rb",
     "lib/interface/layouts/border_layout.rb",
     "lib/interface/layouts/flow_layout.rb",
     "lib/interface/layouts/grid_layout.rb",
     "lib/interface/layouts/layout.rb",
     "lib/interface/managers/frame_location_manager.rb",
     "lib/interface/managers/frame_manager.rb",
     "lib/interface/theme.rb",
     "lib/interface/theme/effects/button_effect.rb",
     "lib/interface/theme/effects/effect.rb",
     "lib/math/dice.rb",
     "lib/math/die.rb",
     "lib/math/vector.rb",
     "lib/open_gl/camera.rb",
     "lib/open_gl/display_list.rb",
     "lib/open_gl/frustum.rb",
     "lib/open_gl/octree.rb",
     "lib/physics/gravity/gravitational_field.rb",
     "lib/physics/gravity/gravity_source.rb",
     "lib/resources/content.rb",
     "lib/resources/image.rb",
     "lib/screen/viewport.rb",
     "lib/textures/font.rb",
     "lib/textures/round_rect_generator.rb",
     "lib/textures/texture.rb",
     "lib/textures/texture_generator.rb",
     "lib/world/actor.rb",
     "lib/world/character/character_class.rb",
     "lib/world/character/language.rb",
     "lib/world/character/race.rb",
     "lib/world/object.rb",
     "lib/world/scene.rb",
     "lib/world/scenes/height_map.rb",
     "test/test_divinity.rb"
  ]
  s.homepage = %q{http://github.com/sinisterchipmunk/divinity}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{A new kind of game engine}
  s.test_files = [
    "test/camera_test.rb",
     "test/frustum_test.rb",
     "test/octree_test.rb",
     "test/test_divinity.rb",
     "test/test_helper.rb",
     "test/unit/extensions/array_test.rb",
     "test/unit/extensions/fixnum_test.rb",
     "test/unit/geometry/vertex3d_test.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_runtime_dependency(%q<activesupport>, [">= 2.3.4"])
      s.add_runtime_dependency(%q<ruby-opengl>, [">= 0.60.1"])
      s.add_runtime_dependency(%q<rmagick>, [">= 2.12.0"])
      s.add_runtime_dependency(%q<rubysdl-mswin32-1.8>, [">= 2.1.0.1"])
    else
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<activesupport>, [">= 2.3.4"])
      s.add_dependency(%q<ruby-opengl>, [">= 0.60.1"])
      s.add_dependency(%q<rmagick>, [">= 2.12.0"])
      s.add_dependency(%q<rubysdl-mswin32-1.8>, [">= 2.1.0.1"])
    end
  else
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<activesupport>, [">= 2.3.4"])
    s.add_dependency(%q<ruby-opengl>, [">= 0.60.1"])
    s.add_dependency(%q<rmagick>, [">= 2.12.0"])
    s.add_dependency(%q<rubysdl-mswin32-1.8>, [">= 2.1.0.1"])
  end
end

