#!/usr/bin/env ruby
ENV['DIVINITY_ENV'] = 'test'
APP_ROOT = File.expand_path(File.join(File.dirname(__FILE__), '..'))

begin
  require 'rubigen'
rescue LoadError
  require 'rubygems'
  require 'rubigen'
end
require 'rubigen/scripts/destroy'

ARGV.shift if ['--help', '-h'].include?(ARGV[0])
RubiGen::Base.use_component_sources! [:divinity]
RubiGen::Scripts::Destroy.new.run(ARGV)
